Syslog              yes
SyslogSuccess       yes
LogWhy              yes

Canonicalization    relaxed/simple
Mode                s
SubDomains          no

AutoRestart         yes
AutoRestartRate     10/1M

Background          yes

UserID              opendkim
UMask               002

Socket              local:/run/opendkim/opendkim.sock

KeyTable            /etc/opendkim/KeyTable
SigningTable        refile:/etc/opendkim/SigningTable
InternalHosts       /etc/opendkim/TrustedHosts
ExternalIgnoreList  /etc/opendkim/TrustedHosts
